import 'jquery';
import 'core-js'

import '../blocks/searchRoom/searchRoom.scss';
import '../blocks/common/common.scss';
import '../blocks/sumGuests/sumGuests.scss';
import '../blocks/buttons/buttons.scss';
import '../blocks/inputs/inputs.scss';
import '../blocks/checkbox/checkbox.scss';
import '../blocks/radio/radio.scss';
import '../blocks/toggle/toggle.scss';
import '../blocks/range/range.scss';
import '../blocks/pagination/pagination.scss';
import '../blocks/rate/rate.scss';
import '../blocks/bulletList/bulletList.scss';
import '../blocks/review/review.scss';
import '../blocks/features/features.scss';
import '../blocks/datapicker/datepicker.scss';
import '../blocks/registration/registration.scss';
import '../blocks/orderRoom/orderRoom.scss';
import '../blocks/cardRoom/cardRoom.scss';
import '../blocks/navBar/navBar.scss';
import '../blocks/copyright/copyright.scss';
import '../blocks/socialButtons/socialButtons.scss';
import '../blocks/footer/footer.scss';
import '../blocks/footerWidget/footerWidget.scss';
import '../blocks/common/index.scss';
import '../blocks/common/registration.scss';
import '../blocks/signIn/signIn.scss';
import '../blocks/common/signIn.scss';

import '../blocks/sumGuests/sumGuests';
import '../blocks/range/range';
import '../blocks/sumGuests/sumRooms';
import '../blocks/checkbox/checkbox';
import '../blocks/datapicker/datepicker';
import '../blocks/registration/registration';
import '../blocks/orderRoom/orderRoom';
import '../blocks/cardRoom/cardRoom';
import '../blocks/navBar/navBar';
import '../blocks/common/index';
import '../blocks/inputs/inputDateRange';

import '../blocks/searchRoom/dataPicker';